version: "3.8"

services:
  app:
    container_name: threadit-dev
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    env_file: ./.env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - REDIS_URL=http://serverless-redis-http:80
    command: sh -c 'source migrate-and-start.sh'
    depends_on:
      - db
      - redis
      - serverless-redis-http
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./.env.local

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    env_file: ./.env.local

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${REDIS_TOKEN}
      SRH_CONNECTION_STRING: "redis://redis:${REDIS_PORT}"
    ports:
      - ${SRH_PORT}:80
    env_file: ./.env.local

volumes:
  postgres_data:
  redis_data:
